Add: Konzeptaufgabe factory_pattern
PM-Dungeon/Assignment-Stubs pull request #5
Opened 2022-03-31 16:58 UTC by jedi101

Add: Konzeptaufgabe factory_pattern

2022-03-31 17:11 UTC, cagix requested changes
- [x] Bitte jeder Datei am Ende noch ein Newline spendieren (der Formatter müsste doch eigentlich auch meckern?) => vgl. Screenshot von der GH-PR-Seite
- [x] Bitte den Ordner umbenennen: Das Ding heisst "Factory-Method-Pattern", also `factory_method` (oder halt komplett `factory_method_pattern`) (ja, ich weiss, das Issue war schon nicht korrekt benannt)
- [ ] Die Review-Kommentare noch umsetzen.

<img width="489" alt="Screenshot 2022-03-31 at 19 03 55" src="https://user-images.githubusercontent.com/20356276/161112023-079c99b5-4a07-439b-ab6f-c932921e9131.png">

<img width="489" alt="Screenshot 2022-03-31 at 19 12 35" src="https://user-images.githubusercontent.com/20356276/161112192-8ba4ef62-13a1-4bdc-8398-1c98668c834c.png">

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Computer.java
> +    Ram ram;
```suggestion
    private Ram ram;
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Computer.java
> +    Drive drive;
```suggestion
    private Drive drive;
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/ComputerFactory.java
> +public class Factory {
```suggestion
public class ComputerFactory {
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Cpu.java
> +    public Cpu(int kerne, float frequency) {
deutsch/englisch? => "kerne" bitte noch übersetzen.

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Drive.java
> +
```suggestion
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Drive.java
> +    private int StorageSize;
```suggestion
    private int storageSize;
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Drive.java
> +    public Drive(int StorageSize) {
```suggestion
    public Drive(int storageSize) {
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Drive.java
> +        this.StorageSize = StorageSize;
```suggestion
        this.storageSize = storageSize;
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Drive.java
> +        return StorageSize;
```suggestion
        return storageSize;
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Hdd.java
> +    public Hdd(int StorageSize) {
```suggestion
    public Hdd(int storageSize) {
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Hdd.java
> +        super(StorageSize);
```suggestion
        super(storageSize);
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Ssd.java
> +    public Ssd(int StorageSize) {
```suggestion
    public Ssd(int storageSize) {
```

2022-03-31 17:11 UTC, cagix commented on factory_pattern/vorgaben/src/Ssd.java
> +        super(StorageSize);
```suggestion
        super(storageSize);
```

2022-03-31 17:34 UTC, jedi101 commented on factory_pattern/vorgaben/src/Cpu.java
> +    private int kerne;
```suggestion
    private int cores;
```

2022-03-31 17:35 UTC, jedi101 commented on factory_pattern/vorgaben/src/Cpu.java
> +    public Cpu(int kerne, float frequency) {
```suggestion
    public Cpu(int cores, float frequency) {
```

2022-03-31 17:43 UTC, jedi101 commented
@cagix - Ich weiß nicht warum der Formatter das nicht macht. Habe den drei mal da drüber laufen lassen weil mir das auch schon mal aufgefallen ist.

2022-03-31 17:48 UTC, cagix commented
> @cagix - Ich weiß nicht warum der Formatter das nicht macht. Habe den drei mal da drüber laufen lassen weil mir das auch schon mal aufgefallen ist. Should be fixed now.

hmm. musste deine ide oder editor richtig einstellen ;) ... vsc hat irgendwo ne einstellung zu dem thema und macht das völlig automatisch.

2022-03-31 17:49 UTC, cagix commented on factory_method_pattern/vorgaben/src/Cpu.java
> +        this.kerne = kerne;
kerne?

2022-03-31 17:49 UTC, cagix commented on factory_method_pattern/vorgaben/src/Cpu.java
> +        return kerne;
kerne?

2022-03-31 17:50 UTC, cagix commented on factory_method_pattern/vorgaben/src/Cpu.java
> +    private int cores;
ist "int" der richtige datentyp für kerne? kann ja auch negativ sein ;) ...

2022-03-31 18:23 UTC, jedi101 commented on factory_method_pattern/vorgaben/src/Cpu.java
> +    private int cores;
wird Zeit für unsigned int in java 24. Ist mir da etwas entgangen und das gibt es schon? Man könnte sich etwas in der art mit einem char zusammen bauen aber... Was machen wir da?

2022-03-31 18:26 UTC, cagix commented on factory_method_pattern/vorgaben/src/Cpu.java
> +    private int cores;
lach

nix. war nur so ein rant :) ... wenn, dann müsstest du dir in java selbst was zusammenklöppeln.

2022-03-31 18:26 UTC, cagix submitted a review, later dismissed
lgtm

2022-03-31 18:27 UTC, cagix commented
habs aber nicht ausgeführt oder so. bitte mal jemand in einer ide aufmachen und "starten"

2022-04-02 10:41 UTC, AMatutat requested changes
bitte einmal das Zwischen.Verzeichnis "vorgaben" entfernen, dann ist es es fine

2022-04-02 11:11 UTC, cagix commented
> bitte einmal das Zwischen.Verzeichnis "vorgaben" entfernen, dann ist es es fine

gut, dass du das gesehen hast. mir ist das gestern durchgerutscht ...

2022-04-02 11:13 UTC, cagix commented
note2self: keine reviews mehr nach 20 uhr, wenn ich um 05 aufgestanden bin

2022-04-03 12:41 UTC, cagix commented
@jedi101 bitte ein erneutes review von @AMatutat oder mir anfordern, wenn du fertig bist ...

2022-04-03 12:43 UTC, jedi101 commented
@cagix - Mache ich sobald ich fertig bin, da ich die "Musterlösung" aber gerade noch überarbeite und ich hier noch einmal gegenchecken wollte ob die Vorgaben alle passen habe ich das bislang noch nicht gemacht obwohl ich den Ordner "Vorgaben" bereits entfernt hatte.

2022-04-03 13:23 UTC, cagix commented
> @cagix - Mache ich dann sobald ich fertig bin. Da ich die "Musterlösung" aber gerade noch überarbeite und ich hier noch einmal gegenchecken wollte ob die Vorgaben alle passen habe ich das bislang noch nicht gemacht obwohl ich den Ordner "Vorgaben" bereits entfernt hatte.

alles gut -- es sah nur fast so aus, als ob du hier fertig bist und ich war unsicher, ob schon jemand drauf schauen soll :)

2022-04-03 18:23 UTC, jedi101 commented
@AMatutat - Bitte noch einmal drauf schauen jetzt, da ich die Musterlösung noch einmal angepasst hatte sind mir 
hier noch ein paar Kleinigkeiten bei der Vorgabe aufgefallen. Habe die Vorgaben deshalb noch einmal an die Aufgabenstellung angepasst. Sonst hätte die Aufgabenstellung noch einmal überarbeitet werden müssen. 
Jetzt sollte aber alles zusammen harmonieren.

2022-04-04 14:02 UTC, merged

2022-04-04 16:57 UTC, cagix commented
@AMatutat Aktualisierst Du dann gleich auch immer das Semester-Repo oder warten wir immer ein paar Änderungen ab und dann? Nur vergessen wäre blöd :)

2022-04-04 18:19 UTC, AMatutat commented
> @AMatutat Aktualisierst Du dann gleich auch immer das Semester-Repo oder warten wir immer ein paar Änderungen ab und dann? Nur vergessen wäre blöd :)

Wollte das einmal pro Woche machen.

2022-04-05 07:40 UTC, cagix commented
> > @AMatutat Aktualisierst Du dann gleich auch immer das Semester-Repo oder warten wir immer ein paar Änderungen ab und dann? Nur vergessen wäre blöd :)
> 
> @cagix Wollte das einmal pro Woche machen.

passt perfekt. wollte das nur mal angesprochen haben :)